[project]
name = "online-debate"
version = "0.3.0"
description = "Online debate management tool"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "colorama>=0.4.6",
    "gspread>=6.1.4",
    "pydrive2>=1.20.0",
    "pyyaml>=6.0.2",
    "requests>=2.32.3",
    "sphinx>=8.1.3",
]
